# Forgejo: quod's self-hosted forge. LAN only.
#
#   Web  http://forgejo.service.consul                       (system Traefik :80 on every node,
#                                                             Consul-catalog tag, plain HTTP)
#   SSH  ssh://git@forgejo.service.consul:2222/<owner>/<repo>.git
#                                                            (static host port on the node
#                                                             that runs the allocation)
#   Data Ceph RBD CSI volume `forgejo-data` at /data: SQLite DB, repositories, LFS,
#        packages, sessions, indexers, and the custom dir /data/gitea.
#
# The allocation may land on any compute node; the RBD volume follows it
# (single-node-writer). No web installer: INSTALL_LOCK is set, registration is
# off, the first admin is created with `forgejo admin user create` (deploy/README.md).
#
# Deploy, from the repo root (file() resolves against the CLI's working directory):
#   NOMAD_ADDR=http://192.168.1.10:4646 nomad job run deploy/forgejo.nomad

variable "forgejo_version" {
  type        = string
  default     = "16.0.5"
  description = "Forgejo image tag on codeberg.org/forgejo/forgejo. Track the latest stable line; bump here to upgrade (https://forgejo.org/releases/)."
}

job "forgejo" {
  datacenters = ["qengho"]
  type        = "service"
  priority    = 60

  group "forgejo" {
    count = 1

    constraint {
      attribute = "${node.class}"
      value     = "compute"
    }

    update {
      max_parallel     = 1
      min_healthy_time = "30s"
      healthy_deadline = "5m"
      auto_revert      = true
    }

    network {
      mode = "bridge"
      port "http" {
        to = 3000
      }
      port "ssh" {
        static = 2222
        to     = 22
      }
    }

    volume "data" {
      type            = "csi"
      source          = "forgejo-data"
      access_mode     = "single-node-writer"
      attachment_mode = "file-system"
    }

    service {
      name = "forgejo"
      port = "http"
      tags = ["forge", "web", "traefik.enable=true"]
      check {
        type     = "http"
        path     = "/api/healthz"
        interval = "15s"
        timeout  = "5s"
      }
    }

    service {
      name = "forgejo-ssh"
      port = "ssh"
      tags = ["forge", "ssh"]
      check {
        type     = "tcp"
        interval = "30s"
        timeout  = "5s"
      }
    }

    # Puts the house theme into the custom dir on the volume before Forgejo starts, so the
    # theme is part of the job spec (deploy/forgejo/theme-quod.css) without a nested bind
    # mount inside the volume. Re-runs on every (re)start; the copy is idempotent.
    task "theme" {
      driver = "docker"

      lifecycle {
        hook    = "prestart"
        sidecar = false
      }

      config {
        image      = "codeberg.org/forgejo/forgejo:${var.forgejo_version}"
        entrypoint = ["/bin/sh", "-c"]
        args = [
          "set -e; mkdir -p /data/gitea/public/assets/css && cp /local/theme-quod.css /data/gitea/public/assets/css/theme-quod.css && echo 'theme-quod.css installed'"
        ]
      }

      volume_mount {
        volume      = "data"
        destination = "/data"
      }

      template {
        data        = file("deploy/forgejo/theme-quod.css")
        destination = "local/theme-quod.css"
        change_mode = "noop"
      }

      resources {
        cpu    = 50
        memory = 32
      }
    }

    task "forgejo" {
      driver = "docker"

      config {
        image = "codeberg.org/forgejo/forgejo:${var.forgejo_version}"
        ports = ["http", "ssh"]
      }

      volume_mount {
        volume      = "data"
        destination = "/data"
      }

      # FORGEJO__<section>__<KEY> is applied to /data/gitea/conf/app.ini on every start by
      # the image's environment-to-ini; the DEFAULT section is the empty name (FORGEJO____KEY).
      # Secrets (SECRET_KEY, INTERNAL_TOKEN, JWT keys) are generated by Forgejo on first boot
      # and live only in app.ini on the volume.
      env {
        USER_UID = "1000"
        USER_GID = "1000"

        FORGEJO____APP_NAME = "quod forge"
        FORGEJO____RUN_MODE = "prod"

        FORGEJO__server__DOMAIN          = "forgejo.service.consul"
        FORGEJO__server__SSH_DOMAIN      = "forgejo.service.consul"
        FORGEJO__server__ROOT_URL        = "http://forgejo.service.consul/"
        FORGEJO__server__HTTP_PORT       = "3000"
        FORGEJO__server__SSH_PORT        = "2222"
        FORGEJO__server__SSH_LISTEN_PORT = "22"

        FORGEJO__database__DB_TYPE             = "sqlite3"
        FORGEJO__database__PATH                = "/data/gitea/forgejo.db"
        FORGEJO__database__SQLITE_JOURNAL_MODE = "WAL"

        FORGEJO__security__INSTALL_LOCK                   = "true"
        FORGEJO__security__REVERSE_PROXY_TRUSTED_PROXIES = "192.168.1.0/24,172.26.64.0/20"

        FORGEJO__service__DISABLE_REGISTRATION = "true"

        FORGEJO__repository__DEFAULT_BRANCH = "master"

        FORGEJO__packages__ENABLED = "true"

        FORGEJO__actions__ENABLED             = "true"
        FORGEJO__actions__DEFAULT_ACTIONS_URL = "https://code.forgejo.org"

        FORGEJO__ui__THEMES        = "forgejo-auto,forgejo-light,forgejo-dark,quod"
        FORGEJO__ui__DEFAULT_THEME = "quod"

        FORGEJO__log__MODE  = "console"
        FORGEJO__log__LEVEL = "info"
      }

      # 768 MiB reserved: Forgejo 16 idles around a quarter of that; git packing, the GitHub
      # migration and the issue indexer spike above it. memory_max lets a spike borrow up to
      # 1.5 GiB from the node's headroom instead of being OOM-killed at the reservation.
      resources {
        cpu        = 500
        memory     = 768
        memory_max = 1536
      }
    }
  }
}
